---
kind: pipeline
type: docker
name: annotation-viewer

steps:
  - name: npm_auth
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: npm_token

  - name: build
    image: node:latest
    commands:
      - yarn install
      - yarn build

  - name: publish
    image: node:latest
    environment:
      GH_TOKEN:
        from_secret: github_token
    commands:
      - npm publish --access public
      - yarn deploy-storybook --ci
    when:
      ref:
        - refs/tags/v*

  - name: announce
    image: plugins/slack
    settings:
      channel: group-dev
      webhook:
        from_secret: slack_webhook
      template: >
        :tada: New version ${DRONE_TAG} of `@committed/annotation-viewer` available
    when:
      ref:
        - refs/tags/v*
      status:
        - success
